ExamenWeb/Controllers/ProduitController.cs
using Data;
using Domain.Entities;
using ExamenWeb.Models;
using Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ExamenWeb.Controllers
{
    public class ProduitController : Controller
    {
        ServiceProduit sp = new ServiceProduit();
        ServiceCategorie sc = new ServiceCategorie();
        ServiceBoutique sb = new ServiceBoutique();


    
        // GET: Product
        public ActionResult ListeProduitFront()
        {
            var prods = sp.GetMany();
            return View(prods);
        }

        // GET: Product/Details/5
        public ActionResult DetailsFront(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit p = sp.GetById((int)id);
            if (p == null)
            {
                return HttpNotFound();
            }
            return View(p);
        }




        //GET: Product
        public ActionResult ListeProduit()
        {
            ExamenContext db = new ExamenContext();

            ////List<Product> listprod = Session["Products"] as List<Product>;
            //var produit = sp.GetMany();

            return View(db.Produits.ToList());
        }

        [HttpPost]
        public ActionResult ListeProduit(String SearchString)
        {
            var produit = sp.GetMany(p => p.Nom.Contains(SearchString));
            return View(produit);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            ProduitModel pm = new ProduitModel();
            //pour recupérer un  champ spécifique  Select(c=>c.name)
            pm.Categories = sc.GetMany().Select(c => new SelectListItem() { Text = c.Nom, Value = c.Id_categorie.ToString() });
            pm.Boutiques = sb.GetMany().Select(b => new SelectListItem() { Text = b.Nom, Value = b.Id_boutique.ToString() });

            return View(pm);
        }




        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(ProduitModel pm, HttpPostedFileBase Image)
        {
            pm.Image = Image.FileName;
            Produit p = new Produit()
            {
                Libelle = pm.Libelle,
                Nom = pm.Nom,
                Quantitee = pm.Quantitee,
                Prix = pm.Prix,
                Description = pm.Description,
                Image = pm.Image,
                Id_categorie = pm.Id_categorie,
                Id_boutique = pm.Id_boutique

            };


            var path = Path.Combine(Server.MapPath("~/Content/Upload/"), Image.FileName);
            Image.SaveAs(path);

        


            try
            {
                // TODO: Add insert logic here
                sp.Add(p);
                // listprod.Add(p);

                // Session["Products"] = listprod;

                sp.Commit();
                return RedirectToAction("ListeProduit");
            }
            catch
            {
                return View();
            }
        }



        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            sp.Commit();
            var produits = sp.GetById(id);
            return View(produits);

        }


        // GET: Produit/Delete/5
        public ActionResult Delete(int id)
        {
            var produits = sp.GetById(id);
            return View(produits);
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var p = sp.GetById(id);
            try
            {
                // TODO: Add delete logic here

                sp.Delete(p);
                sp.Commit();


                return RedirectToAction("ListeProduit");
            }
            catch
            {
                return View();
            }
        }

        // POST: User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit u = sp.GetById((int)id);
            if (u == null)
            {
                return HttpNotFound();
            }
            return View(u);
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Produit u)
        {
            sp.Update(u);
            //db.Entry(avis).State = EntityState.Modified;

            return RedirectToAction("Index");
        }


    }
}

ExamenWeb/Views/Produit/Create.cshtml
@model ExamenWeb.Models.ProduitModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Produit", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row mt">

        <div class="form-horizontal">
            <h4>Produit</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Libelle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Libelle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Libelle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantitee, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantitee, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantitee, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("Image", null, new { type = "file" })
                    @Html.ValidationMessageFor(model => model.Image)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Id_categorie, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Id_categorie, Model.Categories)
                    @Html.ValidationMessageFor(model => model.Id_categorie, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Id_boutique, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Id_boutique, Model.Boutiques)
                    @Html.ValidationMessageFor(model => model.Id_boutique, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>

        </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

ExamenWeb/Views/Produit/Delete.cshtml
@model Domain.Entities.Produit

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categorie.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Boutique.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Boutique.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantitee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantitee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ExamenWeb/Views/Produit/Details.cshtml
@model Domain.Entities.Produit

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>





    <section class="wrapper site-min-height">
       
               
                    <div class="custom-box">
                        <div class="servicetitle">


                            <div>
                                <h4>Produit</h4>

                                <dd>
                                    @{string path = "~/Content/Upload/" + Model.Image;}

                                    <img src="@Url.Content(path)" width="500" height="300">
                                </dd>
                                <br />
                                <dt>
                                    @Html.DisplayNameFor(model => model.Description):
                                
                                    @Html.DisplayFor(model => model.Description)
                                </dd>
                                


                                <hr />
                                <ul class="pricing">

                                    <li>
                                        @Html.DisplayNameFor(model => model.Categorie.Nom):
                                  
                                        @Html.DisplayFor(model => model.Categorie.Nom)
                                    </li>

                                    <li>
                                        @Html.DisplayNameFor(model => model.Boutique.Nom):
                                    
                                        @Html.DisplayFor(model => model.Boutique.Nom)
                                    </li>

                                    <li>
                                        @Html.DisplayNameFor(model => model.Libelle):
                                    
                                        @Html.DisplayFor(model => model.Libelle)
                                    </li>

                                    <li>
                                        @Html.DisplayNameFor(model => model.Nom):
                                    
                                        @Html.DisplayFor(model => model.Nom)
                                    </li>

                                    <li>
                                        @Html.DisplayNameFor(model => model.Prix):
                                    
                                        @Html.DisplayFor(model => model.Prix)
                                    </li>

                                    <li>
                                        @Html.DisplayNameFor(model => model.Quantitee):
                                    
                                        @Html.DisplayFor(model => model.Quantitee)
                                    </li>

                                   </ul>

</div>
                            <p>
                                @Html.ActionLink("Edit", "Edit", new { id = Model.Id_produit }) |
                                @Html.ActionLink("Back to List", "Index")
                            </p>

                            </div>
                        </div>
                   
              
      
    </section>

ExamenWeb/Views/Produit/ListeProduit.cshtml
@model IEnumerable<Domain.Entities.Produit>


@*@{
    ViewBag.Title = "ListeProduit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}*@

<h2>ListeProduit</h2>
@using (Html.BeginForm())
{
    <table>
        <tr>
            <td>
                <div> Serach by name : @Html.TextBox("SearchString")    </div>
            </td>

            <td>
                <input type="submit" value="Search" id="submit" />
            </td>
        </tr>
    </table>
}



@*<div class="container">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
            <input type="text" id="Search" placeholder="Search" class="form-control"/>

        </div>

    </div>
</div>*@


<a class="logout">
    @Html.ActionLink("Create New", "Create")
</a>

<table class="table table-striped table-advance table-hover">

    <tr>
        <th href="basic_table.html#">
            @Html.DisplayNameFor(model => model.Categorie.Nom)
        </th>

        <th href="basic_table.html#">
            @Html.DisplayNameFor(model => model.Boutique.Nom)
        </th>

        <th href="basic_table.html#">
            @Html.DisplayNameFor(model => model.Libelle)
        </th>
        <th href="basic_table.html#">
            @Html.DisplayNameFor(model => model.Nom)
        </th>

        <th href="basic_table.html#">
            @Html.DisplayNameFor(model => model.Prix)$
        </th>

        <th href="basic_table.html#">
            @Html.DisplayNameFor(model => model.Quantitee)
        </th>
        <th href="basic_table.html#">
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th href="basic_table.html#">
            @Html.DisplayNameFor(model => model.Image)
        </th>


        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr class="Search">
        <td>
            @Html.DisplayFor(model => item.Categorie.Nom)
        </td>

        <td>
            @Html.DisplayFor(model => item.Boutique.Nom)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Libelle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nom)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Prix)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Quantitee)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @{string path = "~/Content/Upload/" + item.Image;}

            <img src="@Url.Content(path)" width="50" height="50" />
        </td>



        <td>


            <button class="btn btn-success btn-xs">
                @Html.ActionLink("_", "Edit", new { id = item.Id_produit })
                <i class="fa fa-check"></i>
            </button>

            <button class="btn btn-primary btn-xs">
                @Html.ActionLink("_", "Details", new { id = item.Id_produit })
                <i class="fa fa-pencil"></i>
            </button>

            <button class="btn btn-danger btn-xs">
                @Html.ActionLink("_", "Delete", new { id = item.Id_produit })
                <i class="fa fa-trash-o "></i>
            </button>

</td>
    </tr>
}

</table>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $(document).ready(function () {
        function Contains(test_one, text_two) {
            if (text_one.indexOF(text_two) != -1)
                return true;
        }
        $("#Search").keyup(function () {
            var searchText = $("#Search").val().toLocaleLowerCase();
            $(".Search").each(function () {
                if (!Contains($(this).text().toLocaleLowerCase(), searchText)) {
                    $(this).hide();
                }
                else {
                    $(this).show();
                }
            });
        });
    });


</script>